/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT spectrogram.cdb */

/*  Include Header File  */
#include "spectrogramcfg.h"


#pragma CODE_SECTION(CSL_cfgInit,".text:CSL_cfgInit")

/*  Config Structures */
/*  Handles  */

/*
 *  ======== CSL_cfgInit() ========  
 */
void CSL_cfgInit()
{
}
