//rtdx_vbloop.c RTDX using Visual basic for loop gain control
#include "rtdx_vbloopcfg.h"							//generated by .cdb file
#include "dsk6713_aic23.h"
#include <rtdx.h>                              	//codec-DSK support file
Uint32 fs=DSK6713_AIC23_FREQ_16KHZ;            	//set sampling rate
#define DSK6713_AIC23_INPUT_MIC 0x0015
#define DSK6713_AIC23_INPUT_LINE 0x0011
Uint16 inputsource=DSK6713_AIC23_INPUT_LINE; // select input
int gain = 1;                                   //initial gain value

RTDX_CreateInputChannel(control_channel);   		//create input channel

interrupt void c_int11()                        //ISR
{
 output_sample(gain*input_sample());            //output (input)
}

void main()
{
 comm_intr();												//init codec,DSK,MCBSP
 RTDX_enableInput(&control_channel);            //enable RTDX channel

 while(1)  													//infinite loop
 {
  if(!RTDX_channelBusy(&control_channel))      	//if channel not busy
     RTDX_read(&control_channel,&gain,sizeof(gain));//read gain from PC
 }
}
